name: Validate DNS Zone Files

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies (locked)
        run: uv sync --frozen

      - name: Test zone file merge
        run: uv run python ./merge_zones.py

      - name: Validate merged zone with OctoDNS (dry run)
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN || 'dummy-token' }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID || 'dummy-account' }}
        run: |
          # Only run OctoDNS validation if we have real credentials
          if [ "${{ secrets.CLOUDFLARE_TOKEN }}" != "" ] && [ "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" != "" ]; then
            echo "Running OctoDNS dry-run validation..."
            uv run octodns-sync --config-file=config/production.yaml
          else
            echo "Skipping OctoDNS validation (no credentials available for forks/PRs)"
          fi
